### ISSUE TITLE
Get the result on YouTube 

### ISSUE THREAD

**Issue by chengtianle1997** [wvangansbeke/Sparse-Depth-Completion#23]
@wvangansbeke 

How could I get the result displayed on YouTube?
I am confused about how to transfer these depth and rgb image to a 3D point cloud.

**Comment by wvangansbeke** [comment]
Hi @chengtianle1997,

Indeed, you should first compute the 3D coordinates, knowing the intrinsic calibatrion matrix K and the predicted depth values. Then you can easily change the position of the camera to generate the same viewpoint as in the video. So for a point p, you should first compute, D * K<sup>-1</sup> * p, to obtain the coordinate in 3D (in homogeneous coordinates). Next, you can apply a transformation to the obtained point cloud in order to get the desired viewpoint. I just shifted the y-axis. 

Best,
Wouter
