### ISSUE TITLE
Testing the pretrained model 

### ISSUE THREAD

**Issue by AhmedFakhry47** [wvangansbeke/Sparse-Depth-Completion#9]
I have tested the pretrained model you provided and that was the result I got : 
https://drive.google.com/open?id=154zANBoH7dCJNQIQihpqVDTMM_nsotyd

I wonder if those results are matching what you got , or I did something wrong ? 

in addition to that , I wanna know the fusion technique that you used , is it just the concatenation between RGB input images and lidar depth input before you feed it to the CNN ? or there is something more I don't understand 
Thanks in advance :)

**Comment by wvangansbeke** [comment]
Hi @AhmedFakhry47,

I took the code offline a few days ago. Did you forked or cloned it before that day? Multiple persons told me they got the exact results as reported in the paper with this code. I hope to put it back online in a few days. If it takes too long I can maybe send it to the people who request it. 

Regarding your questions. I just use concatenation between rgb input and lidar depth input before feeding it to the global branch in the framework. You figures look decent. Hard to say what the exact RMSE value is of course.

Best,
Wouter

**Comment by AhmedFakhry47** [comment]
Thank you for your instant reply , Am student and am using your code for learning and academic purposes and I was able to reach your code before you make it offline , I just wanna know if I am testing it right , cause what I got from testing is a black and white pictures ( you can see them in the link I provided ) without color mapping , and should I run kitti loader separately before I get into running the whole training ?. 

Thank you :)

**Comment by wvangansbeke** [comment]
Hi @AhmedFakhry47,

First, I trained on jpg's instead of the original png's (small detail). You can find the code in the kitti loader file. Second, You need to make to sure that the lidar frame corresponds to the correct rgb frame. To achieve this, I  fetch all the paths which I later pass to the dataloaders. You can also find it there but this depends on the file structure that you are using. Feel free the change the keywords, if your file structure is different. 

You probably want colormaps called _plasma_ or _magma_ for you plots provided by matplotlib. 

Best,
Wouter
